application/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import notifications.urls
from .views import about, license, privacy_policy

admin.site.site_header = "Shiorium site administration"

urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path("admin/", admin.site.urls),
    path("users/", include("users.urls")),
    path("", include("posts.urls")),
    path("select2/", include("django_select2.urls")),
    path("about/", about, name="about"),
    path("license/", license, name="license"),
    path("privacypolicy/", privacy_policy, name="privacypolicy"),
    path('captcha/', include('captcha.urls')),
    path("inbox/notifications/", include(notifications.urls, namespace='notifications')),
    path("__reload__/", include("django_browser_reload.urls")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += (path("__debug__/", include("debug_toolbar.urls")),)

posts/urls.py
from django.urls import path
from . import views

app_name = "post"

urlpatterns = [
    path("", views.index, name="index"),
    path("post/create/", views.create_post, name="create"),
    path("post/edit/<int:id>/<str:title>", views.edit_post, name="edit"),
    path("post/read/<int:id>/<str:title>", views.read_post, name="read"),
    path("post/delete/<int:id>/<str:title>", views.delete_post, name="delete"),
    path("post/like/<int:id>/<str:title>", views.like_post, name="like"),
    path("post/report/<int:id>/<str:title>", views.report_post, name="report"),
    path("post/revision/", views.edit_revision, name="revision"),
    path("tag/<slug:slug>", views.tag_post, name="tag"),
    path("tag/", views.tag_index, name="tagindex"),
    path("group/", views.group_index, name="group"),
    path("group/create/", views.create_group, name="groupcreate"),
    path("group/<int:id>/<str:title>", views.group_post, name="grouppost"),
    path("group/follow/<int:id>",views.follow_group,name="likegroup"),
    path(
        "group/edit/<int:id>/<str:title>", views.edit_group, name="groupedit"
    ),
    path(
        "group/delete/<int:id>/<str:title>",
        views.group_delete,
        name="groupdelete",
    ),
    path("comments/<int:id>/<str:title>", views.comment_post, name="comments"),
    path("comments/<int:id>", views.delete_comment, name="deletecomment"),
    path(
        "report/comment/<int:id>", views.report_comment, name="reportcomment"
    ),
    path("notification/", views.notifications_page, name="notification"),
    path("notification/read/<int:id>", views.mark_notification, name="readnotification"),
]

users/urls.py
from django.urls import path, include, reverse_lazy
from django.contrib.auth.views import LoginView, PasswordChangeView
from .forms import LoginForm
from . import views

app_name = "user"
urlpatterns = [
    path("<str:username>", views.profile, name="profile"),
    path("<str:username>/edit", views.edit_profile, name="edit"),
    path("auth/login/", LoginView.as_view(redirect_authenticated_user=True,form_class=LoginForm)),
    path(
        "auth/password_change/",
        PasswordChangeView.as_view(
            template_name="registration/change_password.html",
            success_url=reverse_lazy("post:index"),
        ),
        name="change_password",
    ),
    path("auth/", include("django.contrib.auth.urls")),
    path("auth/signup", views.signup, name="signup"),
]

posts/forms.py
from django import forms
from django.forms import ModelForm
from django_select2 import forms as SelectForm
from .models import (
    Post,
    ReportPost,
    GroupPost,
    Tag,
    CommentPost,
    ReportCommentPost,
)


class TagWidget(SelectForm.ModelSelect2MultipleWidget):
    search_fields = [
        "name__icontains",
    ]


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = (
            "title",
            "tag",
            "cover_image",
            "summary",
            "content",
            "group",
            "chapter_id",
            "is_nsfw",
            "is_complete",
            "is_draft",
        )
        widgets = {"tag": TagWidget}

class EditPostForm(PostForm):
    revision_message = forms.CharField(max_length=50,required=True)

class ReportPostForm(ModelForm):
    class Meta:
        model = ReportPost
        fields = ("reason", "description")


class GroupPostForm(ModelForm):
    class Meta:
        model = GroupPost
        fields = ("title", "description")


class EditGroupPostForm(ModelForm):
    class Meta:
        model = GroupPost
        fields = ("title", "description")


class SearchForm(forms.Form):
    title = forms.CharField(max_length=50, required=True)
    tag = forms.ModelChoiceField(queryset=Tag.objects.all(), required=False)
    complete = forms.BooleanField(initial=True, required=False)


class CommentPostForm(ModelForm):
    class Meta:
        model = CommentPost
        fields = ("content",)


class ReportCommentPostForm(ModelForm):
    class Meta:
        model = ReportCommentPost
        fields = ("reason", "description")

class PostRevisionForm(forms.Form):
    revisions = forms.ModelChoiceField(queryset=None)

posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import (
    HttpRequest,
    JsonResponse,
    HttpResponseForbidden,
    HttpResponseNotFound,
)
from django.conf import settings
from django.contrib import messages
from django.utils import timezone
from django.core.paginator import Paginator
from django.utils.text import slugify
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from markdown import markdown
from bleach import clean
from reversion import create_revision,set_user,set_comment,set_date_created
from reversion.models import Version,Revision
from notifications.signals import notify
from notifications.models import Notification
from application.decorators import not_baned, active_required
from .models import Post, Tag, GroupPost, CommentPost
from .forms import (
    PostForm,
    ReportPostForm,
    GroupPostForm,
    EditGroupPostForm,
    SearchForm,
    CommentPostForm,
    ReportCommentPostForm,
    PostRevisionForm,
    EditPostForm,
)

# Create your views here.


class PostGroup:
    def __init__(self, group_post: list, current_post: Post):
        self.group_post: [Post] = group_post
        self.current_post: Post = current_post
        self.group_post_dict = (
            {_index: post for _index, post in enumerate(group_post)}
            if group_post
            else None
        )

    def get_next(self):
        """get next post in list after current post"""
        if not self.current_post.group:
            return None

        print(self.group_post_dict)

        for index, post in self.group_post_dict.items():
            if self.current_post == post:
                if index >= 0 and index < len(self.group_post_dict) - 1:
                    return self.group_post_dict[index + 1]
                break
        return None

    def __str__(self):
        return f"previous post {self.get_previous()}, next post {self.get_next()}  "

    def get_previous(self):
        """get previous post in list before current post"""
        if not self.current_post.group:
            return None

        for index, post in self.group_post_dict.items():
            if self.current_post == post:
                if index > 0 and index < len(self.group_post_dict) + 1:
                    return self.group_post_dict[index - 1]
                break
        return None

@not_baned
def index(request: HttpRequest):
    form = SearchForm()
    posts = Post.objects.filter(is_draft=False).all()

    page = request.GET.get("page", 1)
    query = request.GET.get("title", None)
    complete = request.GET.get("complete", None)

    if query:
        posts = posts.filter(title__contains=query).all()
    
    if complete:
        posts = posts.filter(is_complete=True).all()
        

    paginator = Paginator(posts, settings.ITEM_PER_PAGE)
    page_obj = paginator.get_page(page)

    if request.method == "POST":
        form = SearchForm(request.POST)
        if form.is_valid():
            query = form.cleaned_data["title"]
            return redirect("post:index", query=query)

    return render(
        request,
        "index.html",
        {
            "title": "Project shiorium ",
            "form": form,
            "is_posts": True,
            "search_placeholder": "Search post title",
            "posts": page_obj,
            "page": page_obj,
        },
    )

@not_baned
def read_post(request: HttpRequest, id, title):
    post = get_object_or_404(Post, id=id)

    if not request.user == post.author and post.is_draft:
        return HttpResponseNotFound()

    # post.content = markdown(post.content)

    group = post.group
    group_post = (
        Post.objects.filter(is_draft=False, group=group)
        .order_by("chapter_id")
        .all()
        if group
        else None
    )

    # posts_by_admin = Post.objects.filter(author=post.author,is_draft=False).all()

    if request.user == post.author and group_post:
        group_post = (
            Post.objects.filter(group=group).order_by("chapter_id").all()
        )
        # posts_by_admin = Post.objects.filter(author=post.author,is_draft=False).order_by("id").all()

    post_group = PostGroup(group_post, post)
    next_post = post_group.get_next()
    previous_post = post_group.get_previous()

    return render(
        request,
        "read.html",
        {
            "title": post.title,
            "post": post,
            "read_post": True,
            "next_post": next_post,
            "previous_post": previous_post,
            "group": group,
            "group_post": group_post,
        },
    )


@login_required
@active_required
@not_baned
def create_post(request: HttpRequest):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.content = clean(
                post.content,
                tags=settings.ALLOWED_HTML_TAGS,
                attributes=settings.ALLOWED_HTML_ATTRIBUTES,
                css_sanitizer=settings.CSS_SANITIZER,
                protocols=["data","https","http"],
            )

            if (
                post.group
                and Post.objects.filter(
                    chapter_id=post.chapter_id, group=post.group
                ).exists()
            ):
                post.chapter_id = (
                    Post.objects.filter(group=post.group).last().chapter_id + 1
                )
            else:
                post.chapter_id = 1
            with create_revision():
                post.save()
                form.save_m2m()
                
                set_user(request.user)
                set_comment("initial save")
                set_date_created(timezone.now())

            return redirect("post:index")

    form = PostForm()
    form.fields["group"].queryset = GroupPost.objects.filter(
        owner=request.user
    ).all()
    form.fields["tag"].queryset = Tag.objects.filter(admin_tag=request.user.is_staff).all()
    return render(
        request, "create.html", {"title": "Create post", "form": form}
    )


@login_required
@active_required
@not_baned
def edit_post(request: HttpRequest, id, title):
    post = Post.objects.filter(id=id).first()
    post_revisions = Version.objects.get_for_object(post)
    
    if not request.user == post.author:
        return HttpResponseNotFound()

    if request.method == "POST":
        form = EditPostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)

            post.content = clean(
                post.content,
                tags=settings.ALLOWED_HTML_TAGS,
                attributes=settings.ALLOWED_HTML_ATTRIBUTES,
                css_sanitizer=settings.CSS_SANITIZER,
                protocols=["data","https","http"],
            )
            print(post.content)

            if (
                post.group
                and Post.objects.filter(
                    chapter_id=post.chapter_id, group=post.group
                ).exists()
            ):
                post.chapter_id = (
                    Post.objects.filter(group=post.group).last().chapter_id + 1
                )
            else:
                post.chapter_id = 1
            with create_revision():
                post.save()
                form.save_m2m()
                revision_message = form.cleaned_data["revision_message"]  
                set_user(request.user)
                set_comment(f"{revision_message} on {timezone.now()}")
                set_date_created(timezone.now())
            return redirect("post:index")

    form = EditPostForm(instance=post)
    form.fields["group"].queryset = GroupPost.objects.filter(
        owner=request.user
    ).all()
    form.fields["tag"].queryset = Tag.objects.filter(admin_tag=request.user.is_staff).all()
    revision_form = PostRevisionForm()
    revision_form.fields["revisions"].queryset = post_revisions
    return render(
        request,
        "create.html",
        {
            "title": "Edit post",
            "form": form,
            "is_draft": post.is_draft,
            "content": post.content,
            "edit": True,
            "revision_form": revision_form,
            "post_revisions": post_revisions,
            "post": post,
        },
    )

@login_required
@active_required
@not_baned
def edit_revision(request: HttpRequest):
    if request.method == "POST":
        id = request.POST["post_id"]
        slug = request.POST["post_slug"]
        Revision.objects.filter(id=request.POST["revision"]).first().revert()
    return redirect("post:read",id=id,title=slug)

@login_required
@active_required
@not_baned
def delete_post(request: HttpRequest, id, title):
    post = get_object_or_404(Post, id=id)
    if post.author == request.user:
        post.delete()
        messages.success(request, f"Post {post} deleted")
        return redirect("post:index")
    else:
        return HttpResponseNotFound()


@login_required
@require_POST
@not_baned
def like_post(request: HttpRequest, id, title):
    post = get_object_or_404(Post, id=id)
    if not request.user in post.likes.all():
        post.likes.add(request.user)
        # if request.user != post.author:
        #     notify.send(request.user,recipient=post.author,verb="Someone like your post",target=post)
        return JsonResponse({"msg": f"{request.user} like {post}"})
    else:
        post.likes.remove(request.user)
        return JsonResponse({"msg": f"{request.user} unlike {post}"})


@login_required
@active_required
@not_baned
def report_post(request: HttpRequest, id, title):
    post = get_object_or_404(Post, id=id)
    form = ReportPostForm()

    if request.method == "POST":
        form = ReportPostForm(request.POST)
        if form.is_valid():
            report = form.save(commit=False)
            report.user = request.user

posts/templates/comment.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block content %}
    <style>
        form{
            margin-top: 1.5rem;
        }
        textarea{
            max-height: 150px;
        }
        .comments{
            min-height: 250px;
            max-height: 350px;
            overflow-y: scroll;
        }
    </style>
    <article>
        <header>
            <hgroup>
                <h1>Comment for {{post.title|title}} </h1>
                <h2>{{comments_count}} comments </h2>
            </hgroup>
        </header>
        <div class="comments">
            {% for comment in comments  %}
                {% include "components/user_comment.html" %}
            {% empty %}
                <center>
                    <h2>No comments</h2>
                </center>
            {% endfor %}
            {% include "components/paginate.html" %}
        </div>
        {% if user.is_authenticated and user.account_confirmed %}
            <form action="" method="post">
                {% csrf_token %}
                <label for="{{form.content.name}}">{{form.content.label}} </label>
                {% render_field form.content placeholder="Your comment" %}
                <button>Comment</button>
            </form>
        {% endif %}
    </article>
{% endblock content %}

posts/templates/create.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block jquery %}
    {{form.media.css}}
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.min.js"></script>
{% endblock jquery %}
{% block content %}
    <style>
        .toolbar{
            height: 2rem;
            padding-top: 0.25rem;
            padding-left: 0.5rem;
            padding-right: 0.5rem;
        }
        .summary{
            height: 150px;
        }
        
    </style>
    {% if edit %}
    <h3>Edit your post</h3>
    {% else %}
    <h3>Write a post</h3>
    {% endif %}
   {% if edit %}
        <article>
            <header>
                <h5>Revision history</h5>
            </header>
            <form method="post" action="{% url 'post:revision'  %}">
                {% csrf_token %}
                <input type="hidden" name="post_id" value="{{post.id}}">
                <input type="hidden" name="post_slug" value="{{post.title|slugify}}">
                <select name="revision" id="">
                    <option value="" selected="">---------</option>
                    {% for revision in post_revisions  %}
                        <option value="{{revision.revision.id}}">{{revision.revision.comment}} </option>
                    {% endfor %}
                </select>
                <small>By reverting, your current changes would not be saved</small>
                <button type="submit">Revert</button>
            </form>
        </article>
    {% endif %} 
    <article>
    <form action="" method="post" x-data="{draft: '{{is_draft|escapejs}}' == 'True'}">
            {% include "components/error.html" %}
            {% if edit %}
                <label for="{{form.revision_message.name}}">Revision messages</label>
                {% render_field form.revision_message  placeholder="Revision messages" %}
                <small>Be sure to have unique and clear revision name</small>
            {% endif %}
            {% csrf_token %}
            <label for="{{form.title.name}}">Post title </label>
            {% render_field form.title  placeholder="Post title" %}
            
            <label for="{{form.cover_image.name}}">Cover image </label>
            {% render_field form.cover_image placeholder="URL to cover image" %}

            <label for="{{form.summary.name}}">Summary(max: 150 charachters) </label>
            {% render_field form.summary  placeholder="Post summary" class="summary" %}
            
            <label for="{{form.tag.name}}">Tag </label>
            {% render_field form.tag  placeholder="Post tag" %}
            <br>
            <br>
            <label for="{{form.group.name}}">Choose group </label>
            {% render_field form.group placeholder="Post group" %}
            <small><a href='{% url 'post:groupcreate' %} '>Add new group </a></small>
            
            {% comment %} <div x-show="in_group.length > 0" x-cloak x-transition>
                {% render_field form.chapter_id  %}
            </div> {% endcomment %}
                        
            <h2>Posts flag</h2>
            <div style="padding-top: 1rem;padding-bottom: 1rem;">
                <label for="form.is_complete.name">
                    {{form.is_complete}}
                    {{form.is_complete.label}}
                </label>
                <label for="form.is_draft.name">
                    {% render_field form.is_draft x-on::change="draft=!draft"   %}
                    {{form.is_draft.label}}
                </label>
                <label for="form.is_nsfw.name">
                    {{form.is_nsfw}}
                    {{form.is_nsfw.label}}
                </label>
            </div>
            
            {% comment %} <div x-data="{content: `{{content}}`,is_preview: false}" style="margin-top: 2.5rem;">
                <button type="button" x-text="is_preview?'Editor':'Preview'" x-on:click="is_preview = !is_preview"></button>
                <div x-show="!is_preview" x-cloak x-transition>
                    <h1 style="padding-bottom: 1rem;">Editor</h1>
                    
                    {% include "components/toolbar.html" %}
                    {% render_field form.content  placeholder="Post content" x-model="content" %}
                    <small>{{form.content.help_text|safe}}</small>
                </div>
                <div x-show="is_preview"  x-cloak x-transition>
                    <h1>Preview</h1>
                    <div class="content" x-html='marked.parse(content)'></div> 
                </div>
            </div> {% endcomment %}
            
            <h1>Content</h1>
            <section>
                {% render_field form.content  placeholder="Post content" id="content"  %}
            </section>
            <script>
                $(document).ready(function() {
                    $('#content').summernote(
                        {
                            toolbar: [
                            ["style", ["style"]],
                            ["font", ["bold", "italic", "underline","strikethrough", "superscript", "subscript","clear"]],
                            ["fontsize", ["fontsize"]],
                            ["color", ["color"]],
                            ["insert",["link","picture","hr"]],
                            ["para", ["paragraph"]],
                            ["height", ["height"]],
                            ["undoredo",["undo","redo"]],
                            ["misc",["help","fullscreen"]]
                            ],
                            styleTags: ["p","blockquote","h1","h2","h3","h4","h5","h6"],
                            height: 500,
                            fontsize: '16',
                            fontSizes: ['8','10','12','14','16','18','20','22','24','26','28','30','32','34','36','38','40','42','44','46','48','50','52'],
                            placeholder: 'Post content',
                            //fontNames: ["Sans-serif","Arial","Times New Roman","Eb Garamond","Helvetica"],
                            //fontNamesIgnoreCheck: ["Eb Garamond"],
                        }
                    );
                  });
                  $('#summernote').summernote('fontName', 'Eb Garamond');


            </script>
            {{form.media.js}}
            <button type="submit" x-text="draft?'Save draft':'{{edit|yesno:"Edit,Publish"}} post' " ></button>
        </form>
    </article>
{% endblock content %}

posts/templates/group.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block content %}
<h3>Add new group</h3>
<article>
    <form action="" method="post">
        {% csrf_token %}
        {% include "components/error.html" %}
        
        {% include "components/forms.html" %}

        {% comment %} {% if form.posts %}
            <label for="{{form.posts.name}} ">{{form.posts.label}}</label>
            {% render_field form.posts placeholder="Group description" %}
            <small>Use ctrl+mouse click to select multiple posts </small>
        {% endif %} {% endcomment %}
        <button type="submit">{{edit|yesno:"Edit,Create"}} group</button>
    </form>
</article>
{% endblock content %}

posts/templates/read.html
{% extends "base.html" %}
{% block meta %}
<meta name="og:title" content="{{post.title|title}}">
<meta name="og:type" content="article">
<meta name="og:url" content="https://{{request.get_host}}{{request.get_full_path}}">
<meta name="og:image" content="{{post.image_url}}">
<meta name="og:description" content="{{post.summary}}">
<meta name="og:article:author" content="{{post.author.username}}">
<meta name="og:article:publish_date" content="{{post.date_published}}">
<meta name="og:article:tag" content="{{post.tag.all|join:","}}">
<meta name="description" content="{{post.summary}}">
{% endblock meta %}
{% block content %}
<section>
    <article>
        {% if user.is_authenticated %}
            {% include "components/post_card_dropdown.html" %}
        {% endif %}
        <hgroup>
            <center>
                <h1>{{post.title|title}}</h1>
                <p>By <a href="{% url 'user:profile' post.author.username %}">{{post.author.username}}</a> at {{post.date_published|date:"j M Y f A T"}}</p>
                {% if post.cover_image %}
                    <img src="{{post.cover_image}} " alt="{{post.title}} cover image " style="width: 100%;height: 350px;" >
                {% endif %}
            </center>
            {% if post.is_draft %}
                <small style="padding-bottom: 1.5rem;">Draft post</small>
            {% endif %}
            {% if post.is_nsfw %}
                <small style="display: block;"><i class="fa-solid fa-triangle-exclamation" style="color: #cc0000;"></i>Nsfw post</small>
            {% endif %}
            <br>
        </hgroup>
        <hr>
        <main style="margin-top: 2rem;margin-bottom: 15rem;">
            {{post.content|safe}}
        </main>
        <footer>
            {% include "components/tag.html" %}
            {% include "components/like.html" %}
            <hr>
            <nav style="padding-bottom: 0rem;">
                <ul>
                    <a href="{% if previous_post %}{% url 'post:read' previous_post.id previous_post.title|slugify %}{% endif %}" {{previous_post|yesno:",disabled"}} class="{{previous_post|yesno:",secondary"}}" title="{{previous_post.is_draft|yesno:"previous post is a draft post,"}}">&laquo;Previous post</a>
                </ul>
                <ul>
                    <a href="{% if next_post %}{% url 'post:read' next_post.id next_post.title|slugify %}{% endif %}" {{next_post|yesno:",disabled"}}  class="{{next_post|yesno:",secondary"}}" title="{{next_post.is_draft|yesno:"next post is a draft post,"}}" >Next post&raquo;</a>
                </ul>
            </nav>
        </footer>
    </article>
</section>
<section>
    <div class="grid">
        {% if group %}
            <article>
                <header>
                    <h2>Other post from group <a href="{% url 'post:grouppost' group.id group.title|slugify %} ">{{group.title|title}} </a> </h2>
                </header>
                <main>
                    {% for post_in_group in group_post|slice:"0,5"  %}
                        {% if post_in_group != post  %}
                            <h2>
                                <a href="{% url 'post:read' post_in_group.id  post_in_group.title|slugify %}">{{post_in_group.title|title}} </a>
                            </h2>
                            {% if post_in_group.is_nsfw %}
                                <small style="display: block;"><i class="fa-solid fa-triangle-exclamation" style="color: #cc0000;"></i>Nsfw post</small>
                            {% endif %}
                            <small>{{post_in_group.is_draft|yesno:"draft post,"}} </small>
                            {% include "components/tag.html" %}
                            <small>Publish at  {{post_in_group.date_published|date:"j M Y"}} </small>
                            <div style="padding-top: 1.5rem">
                                {% include "components/like.html" with post=post_in_group  %}
                            </div>
                            <hr>
                        {% endif %}
                    {% empty %}
                        <center>
                            <h1>No post</h1>
                        </center>
                    {% endfor %}
                </main>
            </article>
        {% endif %}
        {% comment %} <article>
            <header> 
                <h2>Other posts from {{post.author.username}}</h2>
            </header>
        </article> {% endcomment %}
    </div>
</section>
{% endblock content %}

posts/templates/report.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block content %}
    <article>
        {% if comment %}
            <h5>Reporting a comment by <a href="{% url 'user:profile' comment.author.username  %}">{{comment.author.username}}</a> </h5>
        {% else %}
            <h5>Reporting {{post}} by <a href="{% url 'user:profile' post.author.username  %}">{{post.author.username}}</a> </h5>
        {% endif %}
        <form action="" method="post">
            {% csrf_token %}
            {% include "components/error.html" %}
        
            {% include "components/forms.html" %}
            {% if comment  %}
            <button type="submit">Report comment</button>
            {% else %}
            <button type="submit">Report post</button>
            {% endif %}
        </form>
    </article>
{% endblock content %}

posts/templates/tags.html
{% extends "base.html" %}
{% block content %}
    {% include "components/select_page.html" %}
    {% for tag in tags  %} 
        <span style="padding-top: 1rem;padding-bottom: 1rem;">
            <a  class="tag" style="background-color: {{tag.background_color}}" href="{% url 'post:tag' tag.slug %}">#{{tag}}</a> 
        </span>
    {% endfor %}
{% endblock content %}