application/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import notifications.urls
from .views import about, license, privacy_policy

admin.site.site_header = "Shiorium site administration"

urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path("admin/", admin.site.urls),
    path("users/", include("users.urls")),
    path("", include("posts.urls")),
    path("select2/", include("django_select2.urls")),
    path("about/", about, name="about"),
    path("license/", license, name="license"),
    path("privacypolicy/", privacy_policy, name="privacypolicy"),
    path('captcha/', include('captcha.urls')),
    path("inbox/notifications/", include(notifications.urls, namespace='notifications')),
    path("__reload__/", include("django_browser_reload.urls")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += (path("__debug__/", include("debug_toolbar.urls")),)

posts/urls.py
from django.urls import path
from . import views

app_name = "post"

urlpatterns = [
    path("", views.index, name="index"),
    path("post/create/", views.create_post, name="create"),
    path("post/edit/<int:id>/<str:title>", views.edit_post, name="edit"),
    path("post/read/<int:id>/<str:title>", views.read_post, name="read"),
    path("post/delete/<int:id>/<str:title>", views.delete_post, name="delete"),
    path("post/like/<int:id>/<str:title>", views.like_post, name="like"),
    path("post/report/<int:id>/<str:title>", views.report_post, name="report"),
    path("post/revision/", views.edit_revision, name="revision"),
    path("tag/<slug:slug>", views.tag_post, name="tag"),
    path("tag/", views.tag_index, name="tagindex"),
    path("group/", views.group_index, name="group"),
    path("group/create/", views.create_group, name="groupcreate"),
    path("group/<int:id>/<str:title>", views.group_post, name="grouppost"),
    path("group/follow/<int:id>",views.follow_group,name="likegroup"),
    path(
        "group/edit/<int:id>/<str:title>", views.edit_group, name="groupedit"
    ),
    path(
        "group/delete/<int:id>/<str:title>",
        views.group_delete,
        name="groupdelete",
    ),
    path("comments/<int:id>/<str:title>", views.comment_post, name="comments"),
    path("comments/<int:id>", views.delete_comment, name="deletecomment"),
    path(
        "report/comment/<int:id>", views.report_comment, name="reportcomment"
    ),
    path("notification/", views.notifications_page, name="notification"),
    path("notification/read/<int:id>", views.mark_notification, name="readnotification"),
]

users/urls.py
from django.urls import path, include, reverse_lazy
from django.contrib.auth.views import LoginView, PasswordChangeView
from .forms import LoginForm
from . import views

app_name = "user"
urlpatterns = [
    path("<str:username>", views.profile, name="profile"),
    path("<str:username>/edit", views.edit_profile, name="edit"),
    path("auth/login/", LoginView.as_view(redirect_authenticated_user=True,form_class=LoginForm)),
    path(
        "auth/password_change/",
        PasswordChangeView.as_view(
            template_name="registration/change_password.html",
            success_url=reverse_lazy("post:index"),
        ),
        name="change_password",
    ),
    path("auth/", include("django.contrib.auth.urls")),
    path("auth/signup", views.signup, name="signup"),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, Group
from django.utils import timezone
from datetime import timedelta


class Role(models.Model):
    role_name = models.CharField(max_length=15, null=False)
    description = models.TextField(
        max_length=100, default="description of the role"
    )

    def __str__(self):
        return self.role_name


class User(AbstractUser):
    """
    A user model that inherit 'AbstractUser' class and customising email and group field, 
    also adding new field such as profile,show_liked_post,allow_nsfw,show_email and account_confirmed 
    """
    email = models.EmailField(unique=True, max_length=50)
    groups = models.ForeignKey(
        Group,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        verbose_name="role",
    )
    profile = models.TextField(
        max_length=250,
        help_text="Tell about yourself(max: 250 characthers)",
        verbose_name="User profile",
        null=True,
        blank=True,
    )
    ban = models.BooleanField(default=False)
    show_liked_post = models.BooleanField(
        default=False, verbose_name="Show your liked posts publicly"
    )
    allow_nsfw = models.BooleanField(
        default=False, verbose_name="Allow nsfw posts"
    )
    account_confirmed = models.BooleanField(default=False,help_text="confirm user account")
    show_email = models.BooleanField(default=True)

    class Meta:
        ordering = ["id"]

    def __str__(self):
        return self.username

class UserBan(models.Model):
    """
    A model to track user ban period, each user still allowed 
    to login but can't do anything during ban period in website
    """
    BAN_PERIOD_CHOICES = (
        ("1m", "1 Minute"),
        ("5m", "5 Minutes"),
        ("1h", "1 Hour"),
        ("4h", "4 Hours"),
        ("24h", "24 Hours"),
        ("7d", "7 Days"),
        ("30d", "30 Days"),
        ("perma", "Permanent"),
    )
    BAN_CATEGORY_CHOICES = (
        ("SPAM", "Spamming"),
        ("ABUSE", "Abusive Behavior"),
        ("HARASSMENT", "Harassment"),
        ("THREATS", "Threats of Violence"),
        ("IMPERSONATION", "Impersonation"),
        ("COPYRIGHT_INFRINGEMENT", "Copyright Infringement"),
        ("CHEATING", "Cheating"),
        ("VIOLATING_TERMS_OF_SERVICE", "Violating Terms of Service"),
        ("OTHER", "Other"),
    )

    user = models.ForeignKey(User,on_delete=models.CASCADE)
    timestamp = models.DateTimeField(null=False)
    description = models.TextField(null=False)
    ban_period = models.CharField(max_length=50,choices=BAN_PERIOD_CHOICES)
    ban_category = models.CharField(max_length=150,choices=BAN_CATEGORY_CHOICES)
    ban_created = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ["-ban_created"]

    def save(self,*args,**kwargs):
        BAN_PERIODS = {
            "1m": timedelta(minutes=1),
            "5m": timedelta(minutes=5),
            "1h": timedelta(hours=1),
            "4h": timedelta(hours=4),
            "24h": timedelta(hours=24),
            "7d": timedelta(days=7),
            "30d": timedelta(days=30),
            "perma": timedelta(days=999999999),
        }
        
        self.timestamp = timezone.now() + BAN_PERIODS[self.ban_period]
        
        super(UserBan, self).save(*args, **kwargs)
    
    def __str__(self):
        return f"{self.user} ban"
    
class LoginImage(models.Model):
    image_url = models.URLField(help_text="twitter url to an image",null=False,blank=False)
    creator = models.CharField(max_length=50, null=False, blank=False)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" x-data="{theme: localStorage.getItem('main_theme') == 'true' }" x-bind:data-theme="theme? 'light':'dark'" >
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block meta %}{% endblock meta %}
    {% comment %} <link rel="stylesheet" href="{% static 'pico.css' %}"/> {% endcomment %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@picocss/pico@next/css/pico.min.css"/>
    {% comment %} <script src="{% static 'marked.js' %}"></script> {% endcomment %}
    {% comment %} <script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script> {% endcomment %}
    <title>{{title|title}} {% block title %}{% endblock title %} </title>
    {% comment %} <script src="{% static 'alpine.js' %}" defer></script> {% endcomment %}
    <script src="https://cdn.jsdelivr.net/npm/feather-icons/dist/feather.min.js"></script> 
    <script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.13.1/dist/cdn.min.js"></script>
    
    {% block jquery %}{% endblock jquery %}

    <link rel="stylesheet" href="{% static 'custom.css' %}"/>
    <link rel="stylesheet" href="{% static 'tag.css' %}"/>
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.png' %}"/>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=EB+Garamond:wght@500&display=swap" rel="stylesheet"> 
</head>
<body>
    {% comment %} x-data="{theme: localStorage.getItem('theme') == 'true' }" x-bind:data-theme="theme? 'light':'dark'" {% endcomment %}
    {% include "nav.html" %}
    <div style="margin: 1rem;">
        {% include "components/flash_messages.html" %}
    </div>
    <div class="container">
        {% block content %}
        {% endblock content %}
    </div>
    <footer>
        <hr>
        <center>
            <div style="margin-top: 1.5rem;font-size: 15pt;">
                <p style="margin-bottom: 0rem;">Shiorium v0.1.5-beta</p>
                <p>Made with <span style="color:#e68e9e"><i data-feather="heart" ></i></span> using <a href="https://www.djangoproject.com/" target="_blank">Django framework</a></p>
            </d>
            <a href="{% url 'about' %}">About</a>
            |
            <a href="{% url 'privacypolicy' %}">Privacy policy</a>
            |
            <a href="{% url 'license' %}">License</a>
            |
            <a href="https://github.com/AlphaBeta1906/expert-umbrella">Source code</a>
            |
            <a href="https://github.com/AlphaBeta1906/expert-umbrella/issues">Issue report</a>
        </center>
    </footer>
    <script>
        feather.replace();

        function like_post(id,slug){
            fetch(`/post/like/${id}/${slug}`,
                    {
                        method: 'POST',
                        body: {} ,
                        credentials: 'same-origin',
                        headers: {
                            'X-CSRFToken': '{{csrf_token}}'
                        }
                    })
        }
        
        function follow_group(id){
            fetch(`/group/follow/${id}`,
            {
                method: 'POST',
                body: {} ,
                credentials: 'same-origin',
                headers: {
                    'X-CSRFToken': '{{csrf_token}}'
                }
            })
        }
        
        function mark_as_read(id){
            fetch(`/notification/read/${id}`,
            {
                method: 'POST',
                body: {} ,
                credentials: 'same-origin',
                headers: {
                    'X-CSRFToken': '{{csrf_token}}'
                }
            })
        }
      </script>
</body>
</html>

templates/generic.html
{% extends "base.html" %}
{% block content %}
    <article>
        <header>
            <h1>{{title}} </h1>
        </header> 
        {{content|safe}}
    </article>
{% endblock content %}

templates/nav.html
{% load static %}

<article class="nav">
  <nav>
    <ul>
      <li>
        <h3>
          <a href="/" style="position: relative;top: 50%;bottom: 50%;">
            <img src="{% static 'favicon.png' %} " alt="" style="height: 52px;width: 52px;">
            Shiorium    
          </a>
        </h3>
      </li>
    </ul>
    <ul>
        {% if user.is_authenticated  %}
          <li>{% include "components/profile.html" %}</li>
          <li></li>
        {% else %}
          <li>
            <a role="button" class="contrast" x-on:click="theme = !theme;localStorage.setItem('main_theme', theme)">
              <i x-show="theme" data-feather="moon"></i>
              <i x-show="!theme" data-feather="sun"></i>
              {% comment %} <i x-bind:class="theme?'fa-solid fa-moon':'fa-solid fa-sun'"></i> {% endcomment %}
            </a>
          </li>
          <li><a role="button" href="{% url 'user:signup' %}" class="secondary">Signup</a></li>
          <li><a role="button" href="{% url 'user:login' %}" class="primary">Login</a></li>
        {% endif %}
    </ul>
</nav>
</article>

templates/notification.html
{% extends "base.html" %}
{% block content %}
    <ul>
        {% for notification in notifications %}
            <li style="margin: 0;padding: 1rem;" x-data="{read: {{notification.unread|yesno:"false,true"}}  }" x-bind:class="read?'read':''">
                <h3 style="margin-bottom: 0rem;">{{notification.verb}} </h3>
                <p style="margin-top: 0rem;">
                    {{ notification.description }}
                </p>
                On {{notification.timestamp}} UTC
                <br>
                {% comment %} <p>{{notification.level}} </p> {% endcomment %}
                <a x-show="!read"  x-on:click="read=!read;mark_as_read({{notification.id}})">Mark as read</a>
                <hr>
            </li>
        {% empty %}
    </ul>
        <h1 style="text-align: center;">No notification here</h1>
    {% endfor %}
{% endblock content %}

templates/unconfirmed.html
{% extends "base.html" %}
{% block content %}
<center>    
    {% if is_ban %}
        <h3>Your account were banned from this website until {{ban.timestamp}} UTC </h3>
        <p>Reason: {{ban.get_ban_category_display}} </p>
        <p>{{ban.description}} </p>
        <a href="{% url 'user:logout' %}" role="button">Logout</a>
        <br>
        <br>
        {% comment %} <p>Or</p>
        <a href="">File a ban appeal</a> {% endcomment %}
    {% else %}
        <h3>Your account hasn't yet to be confirmed, please wait admin to confirm your account first</h3>
    {% endif %}
</center>
{% endblock content %}