application/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import notifications.urls
from .views import about, license, privacy_policy

admin.site.site_header = "Shiorium site administration"

urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path("admin/", admin.site.urls),
    path("users/", include("users.urls")),
    path("", include("posts.urls")),
    path("select2/", include("django_select2.urls")),
    path("about/", about, name="about"),
    path("license/", license, name="license"),
    path("privacypolicy/", privacy_policy, name="privacypolicy"),
    path('captcha/', include('captcha.urls')),
    path("inbox/notifications/", include(notifications.urls, namespace='notifications')),
    path("__reload__/", include("django_browser_reload.urls")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += (path("__debug__/", include("debug_toolbar.urls")),)

posts/urls.py
from django.urls import path
from . import views

app_name = "post"

urlpatterns = [
    path("", views.index, name="index"),
    path("post/create/", views.create_post, name="create"),
    path("post/edit/<int:id>/<str:title>", views.edit_post, name="edit"),
    path("post/read/<int:id>/<str:title>", views.read_post, name="read"),
    path("post/delete/<int:id>/<str:title>", views.delete_post, name="delete"),
    path("post/like/<int:id>/<str:title>", views.like_post, name="like"),
    path("post/report/<int:id>/<str:title>", views.report_post, name="report"),
    path("post/revision/", views.edit_revision, name="revision"),
    path("tag/<slug:slug>", views.tag_post, name="tag"),
    path("tag/", views.tag_index, name="tagindex"),
    path("group/", views.group_index, name="group"),
    path("group/create/", views.create_group, name="groupcreate"),
    path("group/<int:id>/<str:title>", views.group_post, name="grouppost"),
    path("group/follow/<int:id>",views.follow_group,name="likegroup"),
    path(
        "group/edit/<int:id>/<str:title>", views.edit_group, name="groupedit"
    ),
    path(
        "group/delete/<int:id>/<str:title>",
        views.group_delete,
        name="groupdelete",
    ),
    path("comments/<int:id>/<str:title>", views.comment_post, name="comments"),
    path("comments/<int:id>", views.delete_comment, name="deletecomment"),
    path(
        "report/comment/<int:id>", views.report_comment, name="reportcomment"
    ),
    path("notification/", views.notifications_page, name="notification"),
    path("notification/read/<int:id>", views.mark_notification, name="readnotification"),
]

users/urls.py
from django.urls import path, include, reverse_lazy
from django.contrib.auth.views import LoginView, PasswordChangeView
from .forms import LoginForm
from . import views

app_name = "user"
urlpatterns = [
    path("<str:username>", views.profile, name="profile"),
    path("<str:username>/edit", views.edit_profile, name="edit"),
    path("auth/login/", LoginView.as_view(redirect_authenticated_user=True,form_class=LoginForm)),
    path(
        "auth/password_change/",
        PasswordChangeView.as_view(
            template_name="registration/change_password.html",
            success_url=reverse_lazy("post:index"),
        ),
        name="change_password",
    ),
    path("auth/", include("django.contrib.auth.urls")),
    path("auth/signup", views.signup, name="signup"),
]

posts/forms.py
from django import forms
from django.forms import ModelForm
from django_select2 import forms as SelectForm
from .models import (
    Post,
    ReportPost,
    GroupPost,
    Tag,
    CommentPost,
    ReportCommentPost,
)


class TagWidget(SelectForm.ModelSelect2MultipleWidget):
    search_fields = [
        "name__icontains",
    ]


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = (
            "title",
            "tag",
            "cover_image",
            "summary",
            "content",
            "group",
            "chapter_id",
            "is_nsfw",
            "is_complete",
            "is_draft",
        )
        widgets = {"tag": TagWidget}

class EditPostForm(PostForm):
    revision_message = forms.CharField(max_length=50,required=True)

class ReportPostForm(ModelForm):
    class Meta:
        model = ReportPost
        fields = ("reason", "description")


class GroupPostForm(ModelForm):
    class Meta:
        model = GroupPost
        fields = ("title", "description")


class EditGroupPostForm(ModelForm):
    class Meta:
        model = GroupPost
        fields = ("title", "description")


class SearchForm(forms.Form):
    title = forms.CharField(max_length=50, required=True)
    tag = forms.ModelChoiceField(queryset=Tag.objects.all(), required=False)
    complete = forms.BooleanField(initial=True, required=False)


class CommentPostForm(ModelForm):
    class Meta:
        model = CommentPost
        fields = ("content",)


class ReportCommentPostForm(ModelForm):
    class Meta:
        model = ReportCommentPost
        fields = ("reason", "description")

class PostRevisionForm(forms.Form):
    revisions = forms.ModelChoiceField(queryset=None)

posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import (
    HttpRequest,
    JsonResponse,
    HttpResponseForbidden,
    HttpResponseNotFound,
)
from django.conf import settings
from django.contrib import messages
from django.utils import timezone
from django.core.paginator import Paginator
from django.utils.text import slugify
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from markdown import markdown
from bleach import clean
from reversion import create_revision,set_user,set_comment,set_date_created
from reversion.models import Version,Revision
from notifications.signals import notify
from notifications.models import Notification
from application.decorators import not_baned, active_required
from .models import Post, Tag, GroupPost, CommentPost
from .forms import (
    PostForm,
    ReportPostForm,
    GroupPostForm,
    EditGroupPostForm,
    SearchForm,
    CommentPostForm,
    ReportCommentPostForm,
    PostRevisionForm,
    EditPostForm,
)

# Create your views here.


class PostGroup:
    def __init__(self, group_post: list, current_post: Post):
        self.group_post: [Post] = group_post
        self.current_post: Post = current_post
        self.group_post_dict = (
            {_index: post for _index, post in enumerate(group_post)}
            if group_post
            else None
        )

    def get_next(self):
        """get next post in list after current post"""
        if not self.current_post.group:
            return None

        print(self.group_post_dict)

        for index, post in self.group_post_dict.items():
            if self.current_post == post:
                if index >= 0 and index < len(self.group_post_dict) - 1:
                    return self.group_post_dict[index + 1]
                break
        return None

    def __str__(self):
        return f"previous post {self.get_previous()}, next post {self.get_next()}  "

    def get_previous(self):
        """get previous post in list before current post"""
        if not self.current_post.group:
            return None

        for index, post in self.group_post_dict.items():
            if self.current_post == post:
                if index > 0 and index < len(self.group_post_dict) + 1:
                    return self.group_post_dict[index - 1]
                break
        return None

@not_baned
def index(request: HttpRequest):
    form = SearchForm()
    posts = Post.objects.filter(is_draft=False).all()

    page = request.GET.get("page", 1)
    query = request.GET.get("title", None)
    complete = request.GET.get("complete", None)

    if query:
        posts = posts.filter(title__contains=query).all()
    
    if complete:
        posts = posts.filter(is_complete=True).all()
        

    paginator = Paginator(posts, settings.ITEM_PER_PAGE)
    page_obj = paginator.get_page(page)

    if request.method == "POST":
        form = SearchForm(request.POST)
        if form.is_valid():
            query = form.cleaned_data["title"]
            return redirect("post:index", query=query)

    return render(
        request,
        "index.html",
        {
            "title": "Project shiorium ",
            "form": form,
            "is_posts": True,
            "search_placeholder": "Search post title",
            "posts": page_obj,
            "page": page_obj,
        },
    )

@not_baned
def read_post(request: HttpRequest, id, title):
    post = get_object_or_404(Post, id=id)

    if not request.user == post.author and post.is_draft:
        return HttpResponseNotFound()

    # post.content = markdown(post.content)

    group = post.group
    group_post = (
        Post.objects.filter(is_draft=False, group=group)
        .order_by("chapter_id")
        .all()
        if group
        else None
    )

    # posts_by_admin = Post.objects.filter(author=post.author,is_draft=False).all()

    if request.user == post.author and group_post:
        group_post = (
            Post.objects.filter(group=group).order_by("chapter_id").all()
        )
        # posts_by_admin = Post.objects.filter(author=post.author,is_draft=False).order_by("id").all()

    post_group = PostGroup(group_post, post)
    next_post = post_group.get_next()
    previous_post = post_group.get_previous()

    return render(
        request,
        "read.html",
        {
            "title": post.title,
            "post": post,
            "read_post": True,
            "next_post": next_post,
            "previous_post": previous_post,
            "group": group,
            "group_post": group_post,
        },
    )


@login_required
@active_required
@not_baned
def create_post(request: HttpRequest):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.content = clean(
                post.content,
                tags=settings.ALLOWED_HTML_TAGS,
                attributes=settings.ALLOWED_HTML_ATTRIBUTES,
                css_sanitizer=settings.CSS_SANITIZER,
                protocols=["data","https","http"],
            )

            if (
                post.group
                and Post.objects.filter(
                    chapter_id=post.chapter_id, group=post.group
                ).exists()
            ):
                post.chapter_id = (
                    Post.objects.filter(group=post.group).last().chapter_id + 1
                )
            else:
                post.chapter_id = 1
            with create_revision():
                post.save()
                form.save_m2m()
                
                set_user(request.user)
                set_comment("initial save")
                set_date_created(timezone.now())

            return redirect("post:index")

    form = PostForm()
    form.fields["group"].queryset = GroupPost.objects.filter(
        owner=request.user
    ).all()
    form.fields["tag"].queryset = Tag.objects.filter(admin_tag=request.user.is_staff).all()
    return render(
        request, "create.html", {"title": "Create post", "form": form}
    )


@login_required
@active_required
@not_baned
def edit_post(request: HttpRequest, id, title):
    post = Post.objects.filter(id=id).first()
    post_revisions = Version.objects.get_for_object(post)
    
    if not request.user == post.author:
        return HttpResponseNotFound()

    if request.method == "POST":
        form = EditPostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)

            post.content = clean(
                post.content,
                tags=settings.ALLOWED_HTML_TAGS,
                attributes=settings.ALLOWED_HTML_ATTRIBUTES,
                css_sanitizer=settings.CSS_SANITIZER,
                protocols=["data","https","http"],
            )
            print(post.content)

            if (
                post.group
                and Post.objects.filter(
                    chapter_id=post.chapter_id, group=post.group
                ).exists()
            ):
                post.chapter_id = (
                    Post.objects.filter(group=post.group).last().chapter_id + 1
                )
            else:
                post.chapter_id = 1
            with create_revision():
                post.save()
                form.save_m2m()
                revision_message = form.cleaned_data["revision_message"]  
                set_user(request.user)
                set_comment(f"{revision_message} on {timezone.now()}")
                set_date_created(timezone.now())
            return redirect("post:index")

    form = EditPostForm(instance=post)
    form.fields["group"].queryset = GroupPost.objects.filter(
        owner=request.user
    ).all()
    form.fields["tag"].queryset = Tag.objects.filter(admin_tag=request.user.is_staff).all()
    revision_form = PostRevisionForm()
    revision_form.fields["revisions"].queryset = post_revisions
    return render(
        request,
        "create.html",
        {
            "title": "Edit post",
            "form": form,
            "is_draft": post.is_draft,
            "content": post.content,
            "edit": True,
            "revision_form": revision_form,
            "post_revisions": post_revisions,
            "post": post,
        },
    )

@login_required
@active_required
@not_baned
def edit_revision(request: HttpRequest):
    if request.method == "POST":
        id = request.POST["post_id"]
        slug = request.POST["post_slug"]
        Revision.objects.filter(id=request.POST["revision"]).first().revert()
    return redirect("post:read",id=id,title=slug)

@login_required
@active_required
@not_baned
def delete_post(request: HttpRequest, id, title):
    post = get_object_or_404(Post, id=id)
    if post.author == request.user:
        post.delete()
        messages.success(request, f"Post {post} deleted")
        return redirect("post:index")
    else:
        return HttpResponseNotFound()


@login_required
@require_POST
@not_baned
def like_post(request: HttpRequest, id, title):
    post = get_object_or_404(Post, id=id)
    if not request.user in post.likes.all():
        post.likes.add(request.user)
        # if request.user != post.author:
        #     notify.send(request.user,recipient=post.author,verb="Someone like your post",target=post)
        return JsonResponse({"msg": f"{request.user} like {post}"})
    else:
        post.likes.remove(request.user)
        return JsonResponse({"msg": f"{request.user} unlike {post}"})


@login_required
@active_required
@not_baned
def report_post(request: HttpRequest, id, title):
    post = get_object_or_404(Post, id=id)
    form = ReportPostForm()

    if request.method == "POST":
        form = ReportPostForm(request.POST)
        if form.is_valid():
            report = form.save(commit=False)
            report.user = request.user

posts/templates/components/group_card.html
{% load extras %}

<article style="padding-top:1rem;padding-top:1rem">
    {% if user == group.owner %}
        {% include "components/group_card_dropdown.html" %}
    {% endif %}
    <h1>
        <a class="card_title" href="{% url 'post:grouppost' group.id group.title|slugify %}">{{group.title|title}}</a>
    </h1>
    <main>
        there {{group.post_count|pluralize:"is,are"}} {{group.post_count}} post{{group.post_count|pluralize:"s"}} in this group 
        {% if user == group.owner %}
            <i>
                and {% get_draft_post group user %} post(s) are draft post
            </i>
        {% endif %}
    </main>
    <footer>
        A post group by
        <span class="" x-data="{follow: {% if user in group.followers.all %}true {% else %} false {% endif %},count:  {{group.followers.all|length}}}">
            <a href="{% url 'user:profile' group.owner.username %}">
                {{group.owner.username}}
            </a>
            <br>
            <span x-text="count"></span> Follower
            {% comment %} {% if user != group.owner %}
                <a x-on:click="follow = !follow;count += follow?1:-1;follow_group({{group.id}});" style="cursor: pointer;">
                    + <span x-text="follow? 'Unfollow':'Follow' "></span> Group
                </a>
            {% endif %} {% endcomment %}
        </span> 
    </footer>
</article>

posts/templates/components/group_card_dropdown.html
<nav style="padding-top: 0rem;padding-bottom: 0rem;" x-data="{open: false}" x-bind:class="open? 'modal-is-open modal-is-opening':'modal-is-closing'">
    <ul>
    </ul>
    <ul>
        <li>    
            <details class="dropdown">
                <summary>
                    ...
                </summary>
                <ul dir="rtl">
                    {% if user == group.owner %}
                        <li>
                            <a style="cursor: pointer;" x-on:click="open = !open">
                                Delete
                                <i data-feather="trash" style="color: #cc0000;"></i>
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'post:groupedit' group.id group.title|slugify %}">
                                Edit
                                <i data-feather="edit-2" style="color: #3465a4;"></i>
                            </a>
                        </li>
                    {% endif %}
                </ul>
            </details>
        </li>
    </ul>
    {% include "components/group_delete_modal.html" %}
  </nav>

posts/templates/components/group_delete_modal.html
<dialog x-bind:open="open" @keypress="console.log($event)">
    <article>
      <header>
        <Link  style="cursor: pointer;" aria-label="Close" x-on:click="open = !open" x-transition x-cloak class="close" />
        <p>
          {% comment %} <strong>🗓️ Thank You for Registering!</strong> {% endcomment %}
        </p>
        <h2>Delete confirmation</h2>
      </header>
      <h5>Are you sure to delete this group ({{group}}) ? </h5>
      {% comment %} <p>
        We're excited to have you join us for our
        upcoming event. Please arrive at the museum 
        on time to check in and get started.
      </p>
      <ul>
        <li>Date: Saturday, April 15</li>
        <li>Time: 10:00am - 12:00pm</li>
      </ul> {% endcomment %}
      <a role="button" href="{% url 'post:groupdelete' group.id group.title|slugify %}" class="primary">Yes</a>
      <button class="secondary" x-on:click="open = !open">Cancel</button>
    </article>
</dialog>

posts/templates/components/like.html
{% if user.is_authenticated %}
    <span style="cursor: pointer;" x-data="{like: {% if user in post.likes.all %}true{% else %}false{% endif %},count:  {{post.likes.all|length}} }" x-on:click="like = !like;count += like?1:-1;like_post({{post.id}},'{{post.title|slugify}}')" title="like post">
        <span x-bind:style="like? 'color:#e68e9e': '' ">
            <i data-feather="heart"></i>
        </span>
        <span x-text="count"></span>
    </span>
{% else %}
    <span style="cursor: pointer;" x-data="" title="like post">
        <i class="fa-regular fa-heart" x-on:click="window.location.href = '{% url 'user:login' %}'"></i>
        {{post.likes.all|length}}
    </span>
{% endif %}
<a href="{% url 'post:comments' post.id post.title|slugify  %}" style="padding-left: 1rem;" title="comment">
    <i data-feather="message-circle"></i>
    {{post.comment_count}}
</a>

posts/templates/components/paginate.html
<div class="current">
    Page {{ page.number }} of {{ page.paginator.num_pages }}.
</div>
<center style="margin-bottom:1.5rem">
    <div class="pagination">
        <span class="step-links">
            {% if page.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page.previous_page_number }}">previous</a>
            {% endif %}
    
            {% for i in page_range|default_if_none:page.paginator.get_elided_page_range %}
                {% if page.number == i %}
                    <a href="?page={{i}}" class="page-link" aria-current="page">{{ i }} </a>
                {% else %}
                    {% if i == page.paginator.ELLIPSIS %}
                        <a href="?page={{i}}" class="page-item"><span class="page-link">{{ i }}</span></a>
                    {% else %}
                        <a  href="?page={{i}}" class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></a>
                    {% endif %}
                {% endif %}
            {% endfor %}
    
            {% if page.has_next %}
                <a href="?page={{ page.next_page_number }}">next</a>
                <a href="?page={{ page.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>

</center>

posts/templates/components/post_card.html
<article style="padding-top:1rem;padding-top:1rem">
    {% if user.is_authenticated %}
        {% include "components/post_card_dropdown.html" %}
    {% endif %}
    <h1>
        <a class="card_title" href="{% url 'post:read' post.id post.title|slugify  %}" class="card_title">{{post.title|title}}</a>
    </h1>
    {% if post.is_complete %}
        <small style="padding-bottom: 1.5rem;">Complete</small>
    {% endif %}
    {% if post.is_draft %}
        <small style="padding-bottom: 1.5rem;">Draft post</small>
    {% endif %}
    <main>
        <p>{{post.summary|truncatewords:250}} </p>
        {% include "components/tag.html" %}
        {% include "components/like.html" %}
    </main>
    <footer>
        By
        <span class="">
            <a href="{% url 'user:profile' post.author.username %}">
                {{post.author.username}}
            </a>
        </span> 
        at
        {% comment %} <small x-text='new Date("{{post.date_published|date:"c"}}")'></small> {% endcomment %}
        <span>{{post.date_published|date:"j M Y f A T"}}</span>
    </footer>
</article>

posts/templates/components/post_card_dropdown.html
<nav style="padding-top: 0rem;padding-bottom: 0rem;" x-data="{open: false}" x-bind:class="open? 'modal-is-open modal-is-opening':'modal-is-closing'">
    <ul>
    </ul>
    <ul>
        <li>    
            <details class="dropdown">
                <summary>
                    ...
                </summary>
                <ul dir="rtl">
                    <li>
                        <a href="{% url 'post:report' post.id post.title|slugify %}">
                            Report
                            <i data-feather="flag"></i>
                        </a>
                    </li>
                    {% if user == post.author %}
                        <li>
                            <a style="cursor: pointer;" x-on:click="open = !open">
                                Delete
                                <i data-feather="trash" style="color: #cc0000;"></i>
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'post:edit' post.id post.title|slugify %}">
                                Edit
                                <i data-feather="edit-2" style="color: #3465a4;"></i>
                            </a>
                        </li>
                    {% endif %}
                </ul>
            </details>
        </li>
    </ul>
    {% include "components/post_delete_modal.html" %}
  </nav>

posts/templates/components/post_delete_modal.html
<dialog x-data x-bind:open="open" @keydown.enter="alert('Submitted!')">
    <article>
      <header>
        <Link  style="cursor: pointer;" aria-label="Close" x-on:click="open = !open" x-transition x-cloak class="close" />
        <p>
          {% comment %} <strong>🗓️ Thank You for Registering!</strong> {% endcomment %}
        </p>
        <h2>Delete confirmation</h2>
      </header>
      <h5>Are you sure to delete this post ({{post}}) ? </h5>
      {% comment %} <p>
        We're excited to have you join us for our
        upcoming event. Please arrive at the museum 
        on time to check in and get started.
      </p>
      <ul>
        <li>Date: Saturday, April 15</li>
        <li>Time: 10:00am - 12:00pm</li>
      </ul> {% endcomment %}
      <a role="button" href="{% url 'post:delete' post.id post.title|slugify %}" class="primary">Yes</a>
      <button class="secondary" x-on:click="open = !open">Cancel</button>
    </article>
</dialog>

posts/templates/components/select_page.html
<section>
    {% if not tag and not is_group or not group %}
        <div>
            <a href="{% url 'post:index' %}" role="{% if not groups and not tags%}button{% endif %}">Post</a>
            |
            <a href="{% url 'post:group' %}" role="{% if groups %}button{% endif %}">Post group</a>
            |
            <a href="{% url 'post:tagindex' %}" role="{% if tags %}button{% endif %}">Tags</a>
        </div>
    {% endif %}
</section>

posts/templates/components/tag.html
<p style="padding-top: 1rem;padding-bottom: 1rem;">
    {% for tag in post.tag.all  %} 
        <a  class="tag" style="background-color: {{tag.background_color}}" href="{% url 'post:tag' tag.slug %}">#{{tag}}</a> 
    {% empty %} 
        Untagged 
    {% endfor %}
</p>

posts/templates/components/toolbar.html
<div role="group" style="margin-bottom: 0rem;">
    <button class="toolbar" data-tooltip="Header" type="button" x-on:click="content +=  '#' " >H</button>
    <button class="toolbar" data-tooltip="Italic" type="button" x-on:click="content +=  ' *Text* ' " ><i>I</i></button>
    <button class="toolbar" data-tooltip="Bold" type="button" x-on:click="content +=  ' **Text** ' " ><b>B</b></button>
    <button class="toolbar" data-tooltip="Striketrough" type="button" x-on:click="content +=  ' ~~Text~~ ' " ><strike>S</strike></button>
    <button class="toolbar" data-tooltip="Add link" type="button" x-on:click="content +=  ' [text](link) ' " ><i class="fa-solid fa-link"></i></button>
    <button class="toolbar" data-tooltip="Insert image url" type="button" x-on:click="content +=  ' ![alt text](image link) ' " ><i class="fa-solid fa-image"></i></button>
</div>

posts/templates/components/user_comment.html
{% load gravatar %}
<section x-data="{open: false}" x-bind:class="open? 'modal-is-open modal-is-opening':'modal-is-closing'">
    <p>
        {% gravatar comment.author.email 35 %}
        <a href="{% url 'user:profile' comment.author.username %}">{{comment.author.username}}</a>
    </p>
    <p style="margin-bottom: 0rem;">
        {{comment.content}}
    </p>
    {% comment %} <small>at {% now "Y-m-d H:i" %} </small> {% endcomment %}
    <small>{{post.date_published|date:"j M Y f A T"}}</small>
    <p>
        <a href="{% url 'post:reportcomment' comment.id %}?post_id={{post.id}}&post_title={{post.title|slugify}}" title="report post"><i data-feather="flag"></i></a>
        {% if user.username == comment.author.username %}
            <a style="cursor: pointer;" x-on:click="open = !open">
                <i data-feather="trash" style="color: #cc0000;"></i>
            </a>
        {% endif %}
    </p>
    <hr>
    <dialog x-bind:open="open" @keydown.enter="alert('Submitted!')">
        <article>
          <header>
            <Link  style="cursor: pointer;" aria-label="Close" x-on:click="open = !open" x-transition x-cloak class="close" />
            <p>
              {% comment %} <strong>🗓️ Thank You for Registering!</strong> {% endcomment %}
            </p>
            <h2>Delete confirmation</h2>
          </header>
          <h5>Are you sure to delete your comment ? </h5>
          {% comment %} <p>
            We're excited to have you join us for our
            upcoming event. Please arrive at the museum 
            on time to check in and get started.
          </p>
          <ul>
            <li>Date: Saturday, April 15</li>
            <li>Time: 10:00am - 12:00pm</li>
          </ul> {% endcomment %}
          <a role="button" href="{% url 'post:deletecomment' comment.id %}" class="primary">Yes</a>
          <button class="secondary" x-on:click="open = !open">Cancel</button>
        </article>
    </dialog>
</section>