application/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import notifications.urls
from .views import about, license, privacy_policy

admin.site.site_header = "Shiorium site administration"

urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path("admin/", admin.site.urls),
    path("users/", include("users.urls")),
    path("", include("posts.urls")),
    path("select2/", include("django_select2.urls")),
    path("about/", about, name="about"),
    path("license/", license, name="license"),
    path("privacypolicy/", privacy_policy, name="privacypolicy"),
    path('captcha/', include('captcha.urls')),
    path("inbox/notifications/", include(notifications.urls, namespace='notifications')),
    path("__reload__/", include("django_browser_reload.urls")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += (path("__debug__/", include("debug_toolbar.urls")),)

posts/urls.py
from django.urls import path
from . import views

app_name = "post"

urlpatterns = [
    path("", views.index, name="index"),
    path("post/create/", views.create_post, name="create"),
    path("post/edit/<int:id>/<str:title>", views.edit_post, name="edit"),
    path("post/read/<int:id>/<str:title>", views.read_post, name="read"),
    path("post/delete/<int:id>/<str:title>", views.delete_post, name="delete"),
    path("post/like/<int:id>/<str:title>", views.like_post, name="like"),
    path("post/report/<int:id>/<str:title>", views.report_post, name="report"),
    path("post/revision/", views.edit_revision, name="revision"),
    path("tag/<slug:slug>", views.tag_post, name="tag"),
    path("tag/", views.tag_index, name="tagindex"),
    path("group/", views.group_index, name="group"),
    path("group/create/", views.create_group, name="groupcreate"),
    path("group/<int:id>/<str:title>", views.group_post, name="grouppost"),
    path("group/follow/<int:id>",views.follow_group,name="likegroup"),
    path(
        "group/edit/<int:id>/<str:title>", views.edit_group, name="groupedit"
    ),
    path(
        "group/delete/<int:id>/<str:title>",
        views.group_delete,
        name="groupdelete",
    ),
    path("comments/<int:id>/<str:title>", views.comment_post, name="comments"),
    path("comments/<int:id>", views.delete_comment, name="deletecomment"),
    path(
        "report/comment/<int:id>", views.report_comment, name="reportcomment"
    ),
    path("notification/", views.notifications_page, name="notification"),
    path("notification/read/<int:id>", views.mark_notification, name="readnotification"),
]

users/urls.py
from django.urls import path, include, reverse_lazy
from django.contrib.auth.views import LoginView, PasswordChangeView
from .forms import LoginForm
from . import views

app_name = "user"
urlpatterns = [
    path("<str:username>", views.profile, name="profile"),
    path("<str:username>/edit", views.edit_profile, name="edit"),
    path("auth/login/", LoginView.as_view(redirect_authenticated_user=True,form_class=LoginForm)),
    path(
        "auth/password_change/",
        PasswordChangeView.as_view(
            template_name="registration/change_password.html",
            success_url=reverse_lazy("post:index"),
        ),
        name="change_password",
    ),
    path("auth/", include("django.contrib.auth.urls")),
    path("auth/signup", views.signup, name="signup"),
]

templates/components/error.html
{% if form.errors %}
  <div style="color: red;padding-bottom: 1rem;"> 
  {% for field in form %}
    {% for error in field.errors %}
      <small>{{ error|escape }}</small>
    {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
      <small>{{ error|escape }}</small>
    {% endfor %}
  </div>
{% endif %}

templates/components/flash_messages.html
<style>
    .alert {
        padding: 20px;
        background-color: #0eb036; /* Red */
        color: white;
        margin-bottom: 15px;
        color: white;
      }
    
    .danger{
      background-color: #0eb036; /* Red */
    }
      
      /* The close button */
      .closebtn {
        margin-left: 15px;
        color: white;
        font-weight: bold;
        float: right;
        font-size: 22px;
        line-height: 20px;
        cursor: pointer;
        transition: 0.3s;
      }
      
      /* When moving the mouse over the close button */
      .closebtn:hover {
        color: black;
      }
      .alert p{
        margin-bottom: 0rem;
      }
</style>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <div class="alert {{message.tag}}" x-data="{open: true}" x-show="open" x-transition> 
      <span class="closebtn" x-on:click="open = !open">&times;</span> 
      <p>{{message}}</p>
    </div>
    {% endfor %}
</ul>
{% endif %}

templates/components/forms.html
{% load widget_tweaks %}
{% for field in form  %}
    <label for="{{field.name}}">{{field.label}} </label>
    {% render_field field %}
    <small>{{field.help_text}} </small>
{% endfor %}

templates/components/profile.html
{% load gravatar %}
{% load notifications_tags %}
    <details class="dropdown">
      <summary>
        {% gravatar user.email 35 %}
        {{request.user}}
      </summary>
      <ul>
        <li>
            <a href="{% url 'user:profile' user.username %}">
              <i data-feather="user" style="color: #3465a4;"></i>
              Profile
            </a>
        </li>
        <li>
          <a style="cursor: pointer" x-on:click="theme = !theme;localStorage.setItem('main_theme', theme)">
            <i x-show="theme" data-feather="moon"></i>
            <i x-show="!theme" data-feather="sun"></i>
            {% comment %} <i x-bind:class="theme?'fa-solid fa-moon':'fa-solid fa-sun'"></i> {% endcomment %}
            <span x-text="theme? 'Dark theme': 'Light theme' " ></span>
          </a>
        </li> 
        <li>
          <a href="{% url 'post:create' %}">
            <i data-feather="edit-2" style="color: #3465a4;"></i>
            Write post
          </a>
        </li>
        <li>
          <a href="{% url 'post:groupcreate' %}">
            <i data-feather="book" style="color: #3465a4;"></i>
            Create group
          </a>
        </li>
        <li>
          <a href="{% url 'post:notification' %}" title="you have {% notifications_unread %} unread notification(s) ">
            <i data-feather="bell"></i>
            Notification ({% notifications_unread %})
          </a>
        </li> 
        <li>
          <a href="{% url 'user:logout' %}">
            <i data-feather="log-out" style="color: #ef2929;"></i>
            Logout
          </a>
        </li>
        {% if user.is_staff %}
          <li>
            <a href="{% url 'admin:index' %}">
              Admin dashboard
            </a>
          </li>
        {% endif %}
      </ul>
    </details>